services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm start
    volumes:
      - ./client/src/:/app/src/
      - ./client/public/:/app/public/
    depends_on:
      - server
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
