services:
  server:
      build: ./server
      ports:
        - 5050:5000
      command: npm run dev
      volumes:
        - ./server/src/:/app/src/
  client:
      build: ./client
      ports: 
        - 8080:3000
      command: npm start
      environment:
        - CHOKIDAR_USEPOLLING=true
      volumes: 
        - ./client/src/:/app/src/
        - ./client/public/:/app/public/
  mongodb: 
    image: mongo
    volumes:
      - ./data:/data/db
